// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/widgets.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

Future<void> main() async{
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcJ_55GcmfKbI822x3F8Xg9toj85qWis',
    appId: '1:653089199691:web:cce93057f6a46883ed5fce',
    messagingSenderId: '653089199691',
    projectId: 'tennisscoreapp',
    authDomain: 'tennisscoreapp.firebaseapp.com',
    databaseURL: 'https://tennisscoreapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tennisscoreapp.appspot.com',
    measurementId: 'G-7TBZR01YVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_BM0nNiQQPC1QOZ56JZTdv1n7JQvu83I',
    appId: '1:653089199691:android:b5252992a3a101efed5fce',
    messagingSenderId: '653089199691',
    projectId: 'tennisscoreapp',
    databaseURL: 'https://tennisscoreapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tennisscoreapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5u53AFyAtEu9YMOyzVclkGt918gZ2kic',
    appId: '1:653089199691:ios:0526ced87d8ea7bced5fce',
    messagingSenderId: '653089199691',
    projectId: 'tennisscoreapp',
    databaseURL: 'https://tennisscoreapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tennisscoreapp.appspot.com',
    iosClientId: '653089199691-5rj8vp7lt3vpc8hqdec6h6jm9q3crbed.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennisScoreSystem',
  );
}
